
import asyncio
from typing import Any

from playwright.async_api import (
    Page, 
    TimeoutError as PlaywrightTimeoutError
)
from google.genai.types import (
    Candidate, 
    FunctionCall, 
    FunctionResponse, 
    FunctionResponsePart, 
    FunctionResponseBlob
)

from backend.backend_utils.computer_use.custom import save_product


def denormalize_x(
        x: int,
        screen_width: int
    ) -> int:
    """
    Convert a normalized x coordinate to a pixel value.

    Parameters
    ----------
    x : int
        Normalized x coordinate in the range 0-1000.

    screen_width : int
        Width of the screen in pixels.

    Returns
    -------
    int
        Pixel coordinate corresponding to the normalized x.
    """

    return int(x / 1000 * screen_width)


def denormalize_y(
        y: int,
        screen_height: int
    ) -> int:
    """
    Convert a normalized y coordinate to a pixel value.

    Parameters
    ----------
    y : int
        Normalized y coordinate in the range 0-1000.
    screen_height : int
        Height of the screen in pixels.

    Returns
    -------
    int
        Pixel coordinate corresponding to the normalized y.
    """

    return int(y / 1000 * screen_height)


async def __scroll(
        page: Page,
        direction: str,
        magnitude: int
    ) -> None:
    """
    Scroll the page in a given direction by a specified magnitude.

    Parameters
    ----------
    page : Page
        Playwright page instance to perform the scroll on.

    direction : str
        Scroll direction, one of 'up', 'down', 'left', 'right'.

    magnitude : int
        Number of pixels to scroll.

    Returns
    -------
    None
    """

    match direction:
        case "down":
            await page.mouse.wheel(0, magnitude)

        case "up":
            await page.mouse.wheel(0, -(magnitude))

        case "left":
            await page.mouse.wheel(magnitude, 0)

        case "right": 
            await page.mouse.wheel(-(magnitude), 0)

        case _:
            pass


async def execute_function_calls(
        candidate: Candidate,
        page: Page,
        result_list: list[dict[str, str]]
    ) -> list[tuple[str, dict]]:
    """
    Execute a series of function calls generated by a model 
    candidate.

    Each function call can be a browser interaction, such as
    clicking, typing, scrolling, navigation, or saving a product.
    Results for each action are recorded in a tuple (function_name, 
    result_dict).

    Parameters
    ----------
    candidate : Candidate
        Model output candidate containing function call parts.

    page : Page
        Playwright page used for executing actions.

    result_list : list of dict
        List where saved product entries are appended.

    Returns
    -------
    list of tuple
        Each tuple contains the function name and a dictionary
        representing the result of that function call.
    """

    results: list[tuple[str, dict]] = []
    function_calls: list[FunctionCall] = []

    page_viewport: dict[str, int] = await page.evaluate(
        """
        () => ({
            width: window.innerWidth,
            height: window.innerHeight
        })
        """
    )

    for part in candidate.content.parts:
        if part.function_call:
            function_calls.append(part.function_call)

    for function_call in function_calls:
        action_result: dict = {}
        fname: str | None = function_call.name
        args: dict[str, Any] | None = function_call.args

        try:
            match fname:
                case "click_at":
                    if args:
                        actual_x: int = denormalize_x(
                            args["x"], 
                            page_viewport["width"]
                        )
                        actual_y: int = denormalize_y(
                            args["y"], 
                            page_viewport["height"]
                        )

                        await page.mouse.click(actual_x, actual_y)

                        action_result = {"status": "ok"} 

                case "type_text_at":
                    if args:
                        actual_x = denormalize_x(
                            args["x"], 
                            page_viewport["width"]
                        )
                        actual_y = denormalize_y(
                            args["y"], 
                            page_viewport["height"]
                        )

                        text: str = args["text"]
                        press_enter: bool = args["press_enter"]

                        await page.mouse.click(actual_x, actual_y)

                        await page.keyboard.press("ControlOrMeta+A")
                        await asyncio.sleep(1)
                        await page.keyboard.press("Backspace")

                        await page.keyboard.type(text, delay = 500)
                        await asyncio.sleep(1)
                        
                        if press_enter:
                            await page.keyboard.press("Enter")

                        action_result = {"status": "ok"} 

                case "wait_5_seconds":
                    await page.wait_for_load_state(
                        "networkidle",
                        timeout = 10000
                    )

                    action_result = {"status": "ok"} 

                case "go_back":
                    await page.go_back(
                        timeout = 10000
                    )

                    action_result = {"status": "ok"} 

                case "go_forward":
                    await page.go_forward(
                        timeout = 10000
                    )

                    action_result = {"status": "ok"} 

                case "scroll_document":
                    if args:
                        direction: str = args.get("direction", "down")
                        magnitude: int = 200

                        await __scroll(page, direction, magnitude)

                        action_result = {"status": "ok"} 

                case "scroll_at":
                    if args:
                        x: int = args.get("x", 0)
                        y: int = args.get("y", 0)

                        direction: str = args.get("direction", "down")
                        magnitude: int = args.get("magnitude", 100)

                        await page.mouse.move(x, y)
                        await __scroll(page, direction, magnitude)

                        action_result = {"status": "ok"} 

                case "navigate":
                    if args:
                        url: str = args.get("url", "https://google.com")

                        await page.goto(url)
                        await asyncio.sleep(2)

                        action_result = {"status": "ok"} 

                case "search":
                    await page.goto(
                        "https://google.com",
                        timeout = 10000,
                        wait_until = "networkidle"
                    )

                    action_result = {"status": "ok"} 

                case "save_product":
                    if args:
                        product_entry: dict[str, str] = save_product(
                            name = args.get("name", "N/A"),
                            availability = args.get("availability", "N/A"),
                            price = args.get("price", "N/A"),
                            link = args.get("link", "N/A")
                        )

                        result_list.append(product_entry)

                        action_result = {"status": "saved"}  

                case _:
                    action_result = {"status": "error"}

            await page.wait_for_load_state("networkidle", timeout=10)

        except PlaywrightTimeoutError:
            pass

        except Exception as e:
            action_result = {"error": str(e)}

        results.append((fname, action_result))

    return results


async def get_function_responses(
        page: Page,
        results: list[tuple[str, dict]]
    ) -> list[FunctionResponse]:
    """
    Convert executed function call results into structured 
    `FunctionResponse` objects.

    Takes screenshots and the current page URL for each 
    function response.

    Parameters
    ----------
    page : Page
        Playwright page instance used to capture screenshots.

    results : list of tuple
        List of tuples containing function name and result 
        dictionary.

    Returns
    -------
    list of FunctionResponse
        A list of `FunctionResponse` objects containing
        the function name, response data, and associated 
        screenshot.
    """

    screenshot_bytes = await page.screenshot(type="png")
    current_url = page.url
    function_responses = []

    for name, result in results:
        response_data = {"url": current_url}
        response_data.update(result)

        function_responses.append(
            FunctionResponse(
                name = name,
                response = response_data,
                parts = [
                    FunctionResponsePart(
                        inline_data = FunctionResponseBlob(
                            mime_type = "image/png",
                            data = screenshot_bytes
                        )
                    )
                ]
            )
        )

    return function_responses