
from pydantic import BaseModel
from typing import Literal

from shared.events.metadata import (
    BaseMetadata,
    StoreMetadata
)


class ChatMessageEvent(BaseModel):
    """
    Event representing a chat message exchanged within a conversation.

    This event is used for both user and assistant messages and may
    optionally include store-related metadata for retrieval workflows.

    Attributes
    ----------
    type : Literal["chat.message"]
        Discriminator identifying the event type. Always set to
        `"chat.message"`.

    role : Literal["user", "assistant"]
        Role associated with the message:
        
        - `"user"`: message sent by the end user.
        - `"assistant"`: message generated by the AI assistant.
        
    content : str
        Textual content of the message.

    metadata : BaseMetadata or StoreMetadata
        Metadata associated with the message. May contain:

        - Basic conversation metadata (e.g., `chat_id`).
        - Store-related parameters for product retrieval workflows.

    Notes
    -----
    This model is part of the shared event system and is serialized
    and transported between frontend and backend components.
    """
    
    type: Literal["chat.message"] = "chat.message"
    role: Literal["user", "assistant"]
    content: str
    metadata: BaseMetadata | StoreMetadata