
import os
import sys
import platform
import subprocess
from pathlib import Path


def run_command(cmd, description):
    """Run a command and print status."""
    print(f"📦 {description}...")
    try:
        subprocess.run(cmd, check=True)
        print(f"✅ {description} complete")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Error during {description}: {e}")
        return False

def get_venv_python():
    """Get the path to Python in venv."""
    venv_path = Path(__file__).parent / ".venv"
    
    if platform.system() == "Windowns":
        return venv_path / "Scripts" / "python.exe"
    return venv_path / "bin" / "python"

def check_python_version():
    """Check if Python version is compatible (3.13.x)"""
    version = sys.version_info
    
    if version.major != 3 or version.minor != 13:
        print("=" * 60)
        print("❌ Python 3.13.x is required")
        print(f"   Current version: Python {version.major}.{version.minor}.{version.micro}")
        print("\n   📥 Download Python 3.13 from:")
        print("      https://www.python.org/downloads/")
        print("=" * 60)
        return False
    
    print(f"✓ Python {version.major}.{version.minor}.{version.micro} detected")
    return True

def prompt(question, default=None):
    """Prompt user for input with optional default value."""
    if default:
        question_text = f"{question} [{default}]: "
    else:
        question_text = f"{question}: "
    
    value = input(question_text).strip()
    return value if value else default

def create_env_file():
    """Create .env file for frontend"""
    env_file = Path(__file__).parent / ".env"
    
    if env_file.exists():
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("✓ Keeping existing .env file")
            return True
    
    print("\n" + "="*60)
    print("📝 Frontend Configuration")
    print("="*60)
    print("Press Enter to use default values\n")
    
    # Backend URL
    backend_url = prompt("Backend WebSocket URL", default="ws://localhost:8000/ws/chat")
    
    # Write .env file
    print(f"\n💾 Writing configuration to .env...")
    
    env_content = f"""# Frontend Environment Variables
# Generated by setup_frontend.py

# Backend connection
BACKEND_WS_URL={backend_url}

# Streamlit configuration
STREAMLIT_SERVER_PORT=8501
STREAMLIT_SERVER_ADDRESS=0.0.0.0
"""
    
    env_file.write_text(env_content)
    print("✅ .env file created successfully")
    
    return True

def main():
    print("🔧 Setting up frontend environment...\n")
    
    # Check Python version
    if not check_python_version():
        return 1
    
    # Create venv
    venv_path = Path(__file__).parent / ".venv"
    if not venv_path.exists():
        print("📁 Creating virtual environment...")
        if not run_command(
            [sys.executable, "-m", "venv", ".venv"], 
            "Virtual environment creation"):
            return 1
    else:
        print("✓ Virtual environment already exists")
    
    venv_python = get_venv_python()
    
    # Verify venv python exists
    if not venv_python.exists():
        print(f"❌ Virtual environment Python not found at {venv_python}")
        return 1
    
    # Upgrade pip
    if not run_command([str(venv_python), "-m", "pip", "install", "--upgrade", "pip"], 
                      "Pip upgrade"):
        return 1
    
    # Install package in editable mode
    if not run_command([str(venv_python), "-m", "pip", "install", "-e", "."], 
                      "Package installation"):
        return 1
    
    # Configure .env
    print("\n" + "="*60)
    configure = input("Configure .env? (Y/n): ").lower()
    print("="*60)
    
    if configure in ['', 'y', 'yes']:
        if not create_env_file():
            return 1
    
    print("\n" + "="*60)
    print("✅ Setup complete!")
    print("="*60)
    print("\n🚀 To start the frontend, run: python launch_frontend.py")
    print()
    
    return 0

if __name__ == "__main__":
    sys.exit(main())