
services:
  agent-backend:
    build:
      context: .
      dockerfile: podman/backend/Containerfile

    image: agent-backend:0.0.1

    secrets:
      - autologin-env

    ports:
      - 8080:8080

    volumes:
      - ./logins:/agent_app/logins

    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

    command: python src/ws_agent_server.py

    pod: agent-pod

  agent-frontend:
    build:
      context: .
      dockerfile: podman/frontend/Containerfile

    image: agent-frontend:0.0.1

    ports:
      - 8501:8501

    depends_on:
      - agent-backend

    command: streamlit run ui/agent_ui.py

    pod: agent-pod

secrets:
  autologin-env:
    external: true

pods:
  agent-pod:
    ports:
      - "8080:8080"
      - "8501:8501"