
import os
import sys
import platform
import subprocess
from pathlib import Path


MIN_PY = (3, 13)
MAX_PY = (3, 14)  # esclusivo


def check_python_version():
    v = sys.version_info
    if not (MIN_PY <= (v.major, v.minor) < MAX_PY):
        print(
            f"❌ Python {v.major}.{v.minor} non supportato.\n"
            f"   Richiesto: >= {MIN_PY[0]}.{MIN_PY[1]} e < {MAX_PY[0]}.{MAX_PY[1]}"
        )
        sys.exit(1)

    print(f"✔ Python {v.major}.{v.minor} OK")

def run_command(cmd, description):
    """Run a command and print status."""

    print(f"📦 {description}...")

    try:
        subprocess.run(cmd, check=True)
        print(f"✅ {description} complete")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Error during {description}: {e}")
        return False

def get_venv_python():
    """Get the path to Python in venv."""
    venv_path = Path(".venv")
    if platform.system() == "Windows":
        return venv_path / "Scripts" / "python.exe"
    return venv_path / "bin" / "python"

def prompt(question, default=None, secret=False):
    """Prompt user for input with optional default value."""
    if default:
        question_text = f"{question} [{default}]: "
    else:
        question_text = f"{question}: "
    
    if secret:
        import getpass
        value = getpass.getpass(question_text)
    else:
        value = input(question_text).strip()
    
    return value if value else default

def create_env_file_interactive():
    """Create .env file interactively"""
    env_file = Path(".env")
    
    if env_file.exists():
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("✓ Keeping existing .env file")
            return True
    
    print("\n" + "="*60)
    print("📝 Environment Configuration")
    print("="*60)
    print("Press Enter to use default values\n")
    
    # Collect configuration
    config = {}
    
    # Debug mode
    debug = prompt("Enable debug mode? (true/false)", default="true")
    config['DEBUG'] = debug.lower()
    
    # Log level
    log_level = prompt("Log level (DEBUG/INFO/WARNING/ERROR)", default="INFO")
    config['LOG_LEVEL'] = log_level.upper()
    
    # Google API Key
    print("\n🔑 Google Gemini API Key")
    print("   Get your key at: https://makersuite.google.com/app/apikey")
    api_key = prompt("Google API Key", secret=True)
    config['GOOGLE_API_KEY'] = api_key or "your_api_key_here"
    
    # Server configuration
    print("\n🌐 Server Configuration")
    host = prompt("Server host", default="0.0.0.0")
    config['HOST'] = host
    
    port = prompt("Server port", default="8000")
    config['PORT'] = port
    
    # Playwright
    print("\n🎭 Playwright Configuration")
    headless = prompt("Run browser in headless mode? (true/false)", default="true")
    config['HEADLESS'] = headless.lower()
    
    # Write .env file
    print(f"\n💾 Writing configuration to .env...")
    
    env_content = f"""# Backend Environment Variables
# Generated by setup_backend.py


# Google Gemini API
GOOGLE_API_KEY={config['GOOGLE_API_KEY']}

# Server Configuration
HOST={config['HOST']}
PORT={config['PORT']}

# Playwright
HEADLESS={config['HEADLESS']}
"""
    
    env_file.write_text(env_content)
    print("✅ .env file created successfully")
    
    if config['GOOGLE_API_KEY'] == "your_api_key_here":
        print("\n⚠️  Warning: Remember to add your Google API Key to .env!")
    
    return True

def create_env_file_from_template():
    """Create .env from .env.example without interaction"""
    env_file = Path(".env")
    env_example = Path(".env.example")
    
    if env_file.exists():
        print("✓ .env file already exists")
        return True
    
    if env_example.exists():
        import shutil
        shutil.copy(env_example, env_file)
        print("✅ .env created from .env.example")
        print("⚠️  Please edit .env with your configuration")
        return True
    
    # Fallback: create basic template
    env_file.write_text("""# Backend Environment Variables
DEBUG=true
LOG_LEVEL=INFO
GOOGLE_API_KEY=your_api_key_here
HOST=0.0.0.0
PORT=8000
HEADLESS=true
""")
    print("✅ .env template created")
    print("⚠️  Please edit .env with your configuration")
    return True

def main():
    print("🔧 Setting up backend environment...\n")
    
    # 1. Create venv
    venv_path = Path(".venv")
    if not venv_path.exists():
        print("📁 Creating virtual environment...")
        if not run_command([sys.executable, "-m", "venv", ".venv"], 
                          "Virtual environment creation"):
            return 1
    else:
        print("✓ Virtual environment already exists")
    
    venv_python = get_venv_python()
    
    # 2. Upgrade pip
    if not run_command([str(venv_python), "-m", "pip", "install", "--upgrade", "pip"], 
                      "Pip upgrade"):
        return 1
    
    # 3. Install package in editable mode
    if not run_command([str(venv_python), "-m", "pip", "install", "-e", "."], 
                      "Package installation"):
        return 1
    
    # 4. Install Playwright browsers
    print("🌐 Installing Playwright Chromium browser...")
    if not run_command([str(venv_python), "-m", "playwright", "install", "chromium"],
                      "Playwright browser installation"):
        return 1
    
    # 5. Configure .env
    print("\n" + "="*60)
    configure_mode = input("Configure .env interactively? (Y/n): ").lower()
    print("="*60)
    
    if configure_mode in ['', 'y', 'yes']:
        if not create_env_file_interactive():
            return 1
    else:
        if not create_env_file_from_template():
            return 1
    
    print("\n" + "="*60)
    print("✅ Setup complete!")
    print("="*60)
    print("\n🚀 To start the backend, run: python launch_backend.py")
    print()
    
    return 0

if __name__ == "__main__":
    sys.exit(main())