
FROM python:3.13-slim-bookworm

WORKDIR /agent_app_frontend

COPY ui/requirements.txt .
COPY ui ./ui

RUN apt update
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "ui/agent_ui.py"]